module ChatApp
{
  interface ServerInterface
  {
	
	string connection(in string userName);
    void newMessages(in string roomName, in string message);
    string getMessages(in string roomName);
    string listUsers(in string roomName);
    string listRooms();
    string createNewRooms(in string roomName);
    string joinRoom(in string roomToJoin, in string name);
    string leaveRoom(in string roomToLeave, in string name);
    void disconnect(in string userName, in string roomName);

  };
};