package ChatApp;


/**
* ChatApp/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyInterfaces.idl
* Sunday, August 5, 2018 11:48:44 o'clock PM CST
*/

public interface ServerInterfaceOperations 
{
  String connection (String userName);
  void newMessages (String roomName, String message);
  String getMessages (String roomName);
  String listUsers (String roomName);
  String listRooms ();
  String createNewRooms (String roomName);
  String joinRoom (String roomToJoin, String name);
  String leaveRoom (String roomToLeave, String name);
  void disconnect (String userName, String roomName);
} // interface ServerInterfaceOperations
